# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Osteospermum Soprano White
email: ayyappan.arasu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Osteospermum also commonly known as "African Daisy" have origins from South Africa. 
  This variety grows as shrubs or mounds, and is a perinnial plant often found in warm weather environments. 
  These plants have oval green or gray green leaves. The flowers display strikingly clear white petals with sapphire blue eyes. 
  The shrubs are do not grow too tall and have a spread of 12-14 inches and height of around 8-14 inches. 
  They attract wild life like bees and butterflies and are commonly found in California.
baseurl: "/osteospermum-soprano-white" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
